#!/bin/bash
# ============================================================
#  Sergestiona 2.0 - Nginx + PM2 Configuration Script
#  Designed by Antigravity
#  Run as: bash configure_nginx.sh
# ============================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

APP_DIR="/var/www/html/sergestiona"
BACKEND_DIR="$APP_DIR/backend"
FRONTEND_DIR="$APP_DIR/frontend"
NGINX_CONF="/etc/nginx/conf.d/sergestiona.conf"
SERVER_IP=$(hostname -I | awk '{print $1}')
DOMAIN="virtualidad.usergioarboleda.edu.co"

echo -e "${BLUE}====================================================${NC}"
echo -e "${BLUE}   SERGESTIONA 2.0 - NGINX + PM2 CONFIGURACIÓN     ${NC}"
echo -e "${BLUE}====================================================${NC}\n"

# ─────────────────────────────────────────────
# PASO 1: Corregir permisos de PM2
# ─────────────────────────────────────────────
echo -e "${BLUE}[1/5] Corrigiendo permisos de PM2...${NC}"
sudo mkdir -p /home/moodle/.pm2/logs
sudo mkdir -p /home/moodle/.pm2/pids
sudo mkdir -p /home/moodle/.pm2/modules
sudo chown -R moodle:moodle /home/moodle/.pm2
echo '{}' | sudo tee /home/moodle/.pm2/module_conf.json > /dev/null
sudo chown moodle:moodle /home/moodle/.pm2/module_conf.json
echo -e "${GREEN}Permisos de PM2 corregidos.${NC}\n"

# ─────────────────────────────────────────────
# PASO 2: Instalar dependencias del Backend (Laravel)
# ─────────────────────────────────────────────
echo -e "${BLUE}[2/5] Instalando dependencias del Backend (Laravel)...${NC}"
cd "$BACKEND_DIR"

# Generar .env si no existe
if [ ! -f ".env" ]; then
    echo -e "${YELLOW}  Creando archivo .env desde .env.example...${NC}"
    cp .env.example .env 2>/dev/null || cp .env.production .env 2>/dev/null || echo "APP_NAME=Sergestiona
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://$DOMAIN

LOG_CHANNEL=stack
LOG_LEVEL=error

DB_CONNECTION=sqlite
DB_DATABASE=$BACKEND_DIR/database/database.sqlite

SESSION_DRIVER=file
SESSION_LIFETIME=120
CACHE_DRIVER=file
QUEUE_CONNECTION=sync

SANCTUM_STATEFUL_DOMAINS=$DOMAIN
SESSION_DOMAIN=$DOMAIN
" > .env
fi

# Crear directorio y archivo de base de datos SQLite
mkdir -p "$BACKEND_DIR/database"
touch "$BACKEND_DIR/database/database.sqlite"

# Instalar dependencias de Composer
sudo composer install --no-dev --optimize-autoloader --no-interaction 2>&1 | tail -5

# Generar clave de aplicación si está vacía
php artisan key:generate --force 2>/dev/null || true

# Ejecutar migraciones
php artisan migrate --force 2>/dev/null || true

# Optimizar Laravel para producción
php artisan config:cache
php artisan route:cache
php artisan view:cache

echo -e "${GREEN}Backend (Laravel) configurado.${NC}\n"

# ─────────────────────────────────────────────
# PASO 3: Instalar y compilar Frontend (Next.js)
# ─────────────────────────────────────────────
echo -e "${BLUE}[3/5] Instalando y compilando Frontend (Next.js)...${NC}"
cd "$FRONTEND_DIR"

# Crear .env.local para el frontend si no existe
if [ ! -f ".env.local" ]; then
    echo "NEXT_PUBLIC_API_URL=http://$DOMAIN/api" > .env.local
fi

# Instalar dependencias y compilar
npm install --production=false
npm run build
echo -e "${GREEN}Frontend (Next.js) compilado.${NC}\n"

# ─────────────────────────────────────────────
# PASO 4: Configurar y arrancar PM2
# ─────────────────────────────────────────────
echo -e "${BLUE}[4/5] Configurando PM2 para el Frontend...${NC}"

# Detener procesos previos si existen
pm2 stop sergestiona-frontend 2>/dev/null || true
pm2 delete sergestiona-frontend 2>/dev/null || true

# Arrancar el frontend con PM2
cd "$FRONTEND_DIR"
pm2 start npm --name "sergestiona-frontend" -- start -- -p 3000

# Guardar configuración de PM2
pm2 save

# Configurar PM2 para arrancar con el sistema
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u moodle --hp /home/moodle || true

echo -e "${GREEN}PM2 configurado. Frontend corriendo en puerto 3000.${NC}\n"

# ─────────────────────────────────────────────
# PASO 5: Configurar Nginx
# ─────────────────────────────────────────────
echo -e "${BLUE}[5/5] Configurando Nginx como Reverse Proxy...${NC}"

sudo tee "$NGINX_CONF" > /dev/null <<NGINX_EOF
# Sergestiona 2.0 - Nginx Configuration
# Generated by Antigravity
# App accesible en: http://$DOMAIN/sergestiona

server {
    listen 80;
    server_name $DOMAIN;

    # ─── Backend (Laravel API) via PHP-FPM ───
    # Debe ir ANTES que /sergestiona para tener precedencia
    location /api/ {
        root   $BACKEND_DIR/public;
        index  index.php;

        # Rewrite /api/foo -> /foo para Laravel (Laravel no conoce el prefijo /api/)
        rewrite ^/api/(.*)\$ /\$1 break;

        try_files \$uri \$uri/ /index.php?\$query_string;

        location ~ \.php\$ {
            fastcgi_pass   unix:/run/php-fpm/www.sock;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $BACKEND_DIR/public\$fastcgi_script_name;
            include        fastcgi_params;
        }
    }

    # ─── Servir almacenamiento público (fotos de perfil, etc.) ───
    location /storage/ {
        root   $BACKEND_DIR/public;
        try_files \$uri =404;
    }

    # ─── Frontend (Next.js con basePath=/sergestiona) ───
    # Next.js recibe la ruta completa /sergestiona/... tal como viene
    location /sergestiona {
        proxy_pass         http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection 'upgrade';
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }

    # ─── Seguridad: Bloquear acceso a archivos sensibles ───
    location ~ /\.env  { deny all; return 404; }
    location ~ /\.git  { deny all; return 404; }
    location ~ /database { deny all; return 404; }
}
NGINX_EOF

# Ajustar permisos del directorio de la app
sudo chown -R nginx:nginx "$APP_DIR"
sudo chmod -R 755 "$APP_DIR"
sudo chown -R moodle:apache "$BACKEND_DIR/storage" 2>/dev/null || true
sudo chmod -R 775 "$BACKEND_DIR/storage" 2>/dev/null || true
sudo chown -R moodle:apache "$BACKEND_DIR/bootstrap/cache" 2>/dev/null || true
sudo chmod -R 775 "$BACKEND_DIR/bootstrap/cache" 2>/dev/null || true
sudo chown -R moodle:apache "$BACKEND_DIR/database" 2>/dev/null || true
sudo chmod -R 775 "$BACKEND_DIR/database" 2>/dev/null || true
sudo chmod 664 "$BACKEND_DIR/database/database.sqlite" 2>/dev/null || true

# Configurar SELinux para Nginx (necesario en RHEL)
sudo setsebool -P httpd_can_network_connect 1 2>/dev/null || true
sudo setsebool -P httpd_unified 1 2>/dev/null || true

# Probar y recargar Nginx
if sudo nginx -t; then
    sudo systemctl enable nginx
    sudo systemctl restart nginx
    echo -e "${GREEN}Nginx configurado y activo.${NC}\n"
else
    echo -e "${RED}ERROR: La configuración de Nginx tiene errores. Revisa el archivo: $NGINX_CONF${NC}"
    exit 1
fi

# ─────────────────────────────────────────────
# RESUMEN FINAL
# ─────────────────────────────────────────────
echo -e "${BLUE}====================================================${NC}"
echo -e "${GREEN}   CONFIGURACIÓN COMPLETA - SERGESTIONA 2.0        ${NC}"
echo -e "${BLUE}====================================================${NC}"
echo ""
echo -e "  Frontend (Next.js):    http://$DOMAIN/sergestiona"
echo -e "  Backend API (Laravel): http://$DOMAIN/api"
echo ""
echo -e "  Estado PM2:        $(pm2 list 2>/dev/null | grep sergestiona || echo 'Verificar con: pm2 list')"
echo -e "  Estado Nginx:      $(sudo systemctl is-active nginx)"
echo ""
echo -e "${YELLOW}  Próximo paso recomendado: Configurar HTTPS con Certbot${NC}"
echo -e "${YELLOW}  sudo dnf install -y certbot python3-certbot-nginx${NC}"
echo ""
